### ISSUE TITLE
Loading of sass-brunch failed due to Cannot set property getDependencies

### ISSUE THREAD

**Issue by caleb531** [brunch/sass-brunch#148]
Hi,

I'm testing the latest sass-brunch (7ffb2e6ebb7380f920a2f594476a3db0654b11b9) on one of my projects in an attempt to patch brunch/postcss-brunch#33 However, sass-brunch fails to load (with and without postcss-brunch).

Upon running `LOGGY_STACKS=1 brunch build`, I receive the following:

```
warn: Loading of sass-brunch failed due to Cannot set property getDependencies of #<SassCompiler> which has only a getter
  at Object.keys.forEach.key (/Users/Caleb/Repositories/connect-four/node_modules/brunch/lib/utils/plugin-adapter.js:49:17)
  at Array.forEach (native)
  at normMethods (/Users/Caleb/Repositories/connect-four/node_modules/brunch/lib/utils/plugin-adapter.js:42:24)
  at module.exports.plugin (/Users/Caleb/Repositories/connect-four/node_modules/brunch/lib/utils/plugin-adapter.js:103:3)
  at deps.reduce (/Users/Caleb/Repositories/connect-four/node_modules/brunch/lib/utils/plugins.js:82:22)
  at Array.reduce (native)
  at plugins (/Users/Caleb/Repositories/connect-four/node_modules/brunch/lib/utils/plugins.js:76:24)
  at BrunchWatcher.application.loadConfig.then.cfg (/Users/Caleb/Repositories/connect-four/node_modules/brunch/lib/watch.js:112:11)
```

Looking at the blame for `index.js`, the getDependencies getter was added in the very latest commit 9 days ago (7ffb2e6ebb7380f920a2f594476a3db0654b11b9).

**Comment by shvaikalesh** [comment]
Hey @caleb531, thanks for the report. It is definitely a bug in Brunch. Please, check whether https://github.com/brunch/brunch/pull/1683/files fixes it.

**Comment by caleb531** [comment]
@shvaikalesh I can confirm that brunch/brunch#1683 fixes this issue completely. When could I hope to see it merged in? :)

Either way, you're welcome to close this issue now.

**Comment by shvaikalesh** [comment]
Now in `master`.

**Comment by paulmillr** [comment]
Will push a new release today.
