### ISSUE TITLE
Partial .scss files are compiled although they were not included in main .scss file

### ISSUE THREAD

**Issue by jualoppaz** [brunch/sass-brunch#180]
Hi!

I am starting a new brunch project after so long time.

By the moment I have the following scss structure:

styles/
├──features/
├──├──directives/
├──├──├──loading/
├──├──├──├──_loading.scss
├──lib/
├──├──_global.scss
├──├──_globalLasts.scss
├──├──_variables.scss
├──views/
├──├──_gallery.scss
├──├──_home.scss
├──styles.scss

The **styles.scss** content is:

```
// Libraries
@import "lib/variables";
@import "lib/global";

// Components
@import "features/directives/loading/loading";

// Layouts

// Views
@import "views/gallery";
@import "views/home";

@import "lib/globalLasts";
```

My **brunch-config.js** file is the fllowing one:

```
exports.config = {
    npm: {
        enabled: false
    },
    fileListInterval: 2000,
    files: {
        javascripts: {
            joinTo: {
                'js/app.js': /^app(\/|\\)angular/,
                'js/vendor.js': /^(app(\/|\\)vendor|bower_components)/
            },
            order: {
                before: [
                    'bower_components/angular/angular.js',
                    'bower_components/angular-ui-router/release/angular-ui-router.js',
                    'bower_components/angular-animate/angular-animate.js',
                    'bower_components/angular-touch/angular-touch.js',
                    'bower_components/angular-bootstrap/ui-bootstrap-tpls.js',
                ],
                after: [
                    'app/angular/router/router.js',
                    'app/angular/app.js'
                ]
            }
        },
        stylesheets: {
            order: {
                before: []
            },
            joinTo: {
                'css/app.css': /^app(\/|\\)angular(\/|\\)styles/,
                'css/vendor.css': /^(app(\/|\\)vendor|bower_components)/
            }
        },
        templates: {
            joinTo: {
                'js/templates.js': /^app(\/|\\)angular(\/|\\)views/
            }
        }
    },
    modules: {
        wrapper: false,
        definition: false
    },
    plugins: {
        jshint: {
            pattern: /^app(\/|\\)angular(\/|\\).*\.js$/,
            options: {
                strict: true,
                bitwise: true,
                curly: true,
                unused: true,
                eqeqeq: true
            },
            warnOnly: true
        },
        digest: {
            alwaysRun: false,
            environments: ['production']
        },
        afterBrunch: [
            'rm -f public/config/config_*.json',
            'cp bower_components/components-font-awesome/fonts/* public/fonts',
            'cp bower_components/bootstrap/fonts/* public/fonts'
        ],
        uglify: {
            mangle: false
        },
        browserSync: {
            watch: true,
            port: 3333,
            logLevel: "debug"
        }
    },
    // Configuracion especifica del servidor NodeJS utilizado mediante Brunch
    server: {
        path: 'app.js',
        port: 3333,
        base: '/'
    }
};
```

I remember that the correct way is define a main file (**style.scss**) and other like partials (starting with underscore: _). 

However, I am getting an error when compiling my brunch project, because I am using a $color variable in **_loading.scss** file that is declared in **lib/_variables.scss** file.

I tried to comment all @imports from my **styles.scss** file and I saw that the partials file are compiled always, although I don't add them yo my main file.

I reviewed the docs and I can see that the partial files are ignored if they starts with underscore.

The version of **sass-brunch** I am using is **2.10.7**.

Am I doing something wrong? Or there is now another way for ignore the partials file?

Thank you so much.

**Comment by paulmillr** [comment]
we have some kind of bug in 2.10.7 that was not present in 2.10.5

**Comment by paulmillr** [comment]
we just need to fix this in 2.10.7

**Comment by dlepaux** [comment]
Hello, same error but i have downgrade to 2.10.4 because 2.10.5 cause ELIFECYCLE error.. :(

**Comment by paulmillr** [comment]
@designermonkey i'm saying *we **need** to fix this after 2.10.7*, not that it has been fixed.

**Comment by dlepaux** [comment]
@paulmillr Hello !
I would like to fix the issue, but in local the tests won't pass successfully ! I got this in my cli :
```
N30026:sass-brunch dlepaux$ npm run test

> sass-brunch@2.10.7 test /Users/dlepaux/code/sass-brunch
> eslint index.js && mocha



  sass-brunch plugin using
    native
      ✓ should be an object
      ✓ should have a #compile method
      ✓ should compile and produce valid result for scss
      ✓ should default to five decimals of precision for scss
      ✓ should calculate to the indicated level of precision for scss
      ✓ should compile and produce valid result for sass
      ✓ should default to five decimals of precision for sass
      ✓ should calculate to the indicated level of precision for sass
      1) should output valid deps
      ✓ should return empty result for empty source
      ✓ should save without error
      ✓ should compile with modules
      ✓ should skip modulifying files passed to ignore
    ruby
      ✓ should be an object
      ✓ should have a #compile method
You need to have Sass on your system
Execute `gem install sass`
      ✓ should compile and produce valid result for scss
You need to have Sass on your system
Execute `gem install sass`
      ✓ should default to five decimals of precision for scss
You need to have Sass on your system
Execute `gem install sass`
      ✓ should calculate to the indicated level of precision for scss
You need to have Sass on your system
Execute `gem install sass`
      ✓ should compile and produce valid result for sass
You need to have Sass on your system
Execute `gem install sass`
      ✓ should default to five decimals of precision for sass
You need to have Sass on your system
Execute `gem install sass`
      2) should calculate to the indicated level of precision for sass
      3) should output valid deps
      ✓ should return empty result for empty source
You need to have Sass on your system
Execute `gem install sass`
      ✓ should save without error
You need to have Sass on your system
Execute `gem install sass`
      ✓ should compile with modules
You need to have Sass on your system
Execute `gem install sass`
      ✓ should skip modulifying files passed to ignore

  sass-brunch plugin using native
    4) should import files via glob
    with experimental custom functions
      ✓ should invoke the functions for scss
      ✓ should invoke the functions for sass


  25 passing (4s)
  4 failing

  1) sass-brunch plugin using
       native
         should output valid deps:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/dlepaux/code/sass-brunch/test.js)
  

  2) sass-brunch plugin using
       ruby
         should calculate to the indicated level of precision for sass:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/dlepaux/code/sass-brunch/test.js)
  

  3) sass-brunch plugin using
       ruby
         should output valid deps:
     Error: EEXIST: file already exists, mkdir 'app'
      at Object.mkdirSync (fs.js:731:3)
      at Context.done (test.js:146:10)

  4) sass-brunch plugin using native
       should import files via glob:
     Error: EEXIST: file already exists, mkdir 'app'
      at Object.mkdirSync (fs.js:731:3)
      at Context.it (test.js:273:8)



npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! sass-brunch@2.10.7 test: `eslint index.js && mocha`
npm ERR! Exit status 4
npm ERR! 
npm ERR! Failed at the sass-brunch@2.10.7 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dlepaux/.npm/_logs/2018-11-05T12_33_11_092Z-debug.log
```

BTW do you have some documentation about your this._progeny stuff ? 
Thank you

**Comment by designermonkey** [comment]
@paulmillr ah ok, I misunderstood as it read differently, thanks for clarifying it though :)
