### ISSUE TITLE
Issue with node 12

### ISSUE THREAD

**Issue by Cryde** [brunch/sass-brunch#184]
Hello

I have an issues when ```npm ci``` with node 12
```
make : on entre dans le répertoire « /home/jeremy/PhpstormProjects/xxx/node_modules/node-sass/build »
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.4"' -I/home/jeremy/.node-gyp/12.1.0/include/node -I/home/jeremy/.node-gyp/12.1.0/src -I/home/jeremy/.node-gyp/12.1.0/deps/openssl/config -I/home/jeremy/.node-gyp/12.1.0/deps/openssl/openssl/include -I/home/jeremy/.node-gyp/12.1.0/deps/uv/include -I/home/jeremy/.node-gyp/12.1.0/deps/zlib -I/home/jeremy/.node-gyp/12.1.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++1y -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
make: g++ : commande introuvable
src/libsass.target.mk:156 : la recette pour la cible « Release/obj.target/libsass/src/libsass/src/ast.o » a échouée
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Erreur 127
make : on quitte le répertoire « /home/jeremy/PhpstormProjects/xxx/node_modules/node-sass/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jeremy/PhpstormProjects/xxx/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.19.0-0.bpo.1-amd64
gyp ERR! command "/home/jeremy/.nvm/versions/node/v12.1.0/bin/node" "/home/jeremy/PhpstormProjects/xxx/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/jeremy/PhpstormProjects/xxx/node_modules/node-sass
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeremy/.npm/_logs/2019-04-29T15_18_14_581Z-debug.log

```
I guess it's because this lib is stuck with node-sass 4.9.4.
They have update it to supporte node 12 : https://github.com/sass/node-sass/releases/tag/v4.12.0

Could I update to 4.12.0 and then pull request it ?

**Comment by azmeuk** [comment]
```make: g++ : commande introuvable``` suggests that you do not have `g++` installed.

**Comment by Cryde** [comment]
I moved from brunch to webpack so I don't know if it's still relevant.

But as I mentionned It was also a "bug" related to node-sass

**Comment by reubano** [comment]
`npm i --save-dev https://github.com/brunch/sass-brunch\#e31bfe4eb559796a6b0a6be906377ff785785dc4` worked for me.

**Comment by jkruse** [comment]
Version 3.0.0 was since released, and fixes this issue. Time to close?
