### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by fedegratti** [brunch/sass-brunch#187]
maybe it's related to [this issue](https://github.com/sass/node-sass/issues/2662#issuecomment-489268738).

Here's the full stack:
```
C:\Users\Federico\Documents\Projects\eugenius_app>npm install

> node-sass@4.9.4 install C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.9.4 postinstall C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.13.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n' +
gyp verb `which` failed     '    at getNotFoundError (C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Federico\\Documents\\Projects\\eugenius_app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Federico\Documents\Projects\eugenius_app\node_modules\node-sass
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN The package glslify-brunch is included as both a dev and production dependency.
npm WARN The package javascript-brunch is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Federico\AppData\Roaming\npm-cache\_logs\2019-11-19T01_50_13_328Z-debug.log
```

**Comment by boazblake** [comment]
whats the status on this?

**Comment by fedegratti** [comment]
I downgrade from node 12 to node 10 so I could do a successful `npm install`

**Comment by juulSme** [comment]
Because erlang:22-alpine has upgraded its base image to alpine:3.11, and elixir:alpine depends on it, builds are breaking for Elixix/Phoenix applications that use Brunch (and brunch-sass). It would really help if brunch-sass no longer depended on node-sass 4.9.4.

**Comment by juulSme** [comment]
It appears this issue is already fixed on the master branch, the node dependency on node-sass `~4.9.2` that still exists here https://github.com/brunch/sass-brunch/blob/2.10.8/package.json is no longer present. @paulmillr is it possible to create a release of the package with just the higher node-sass dependency? It should work as-is, right? This is currently breaking builds of our Elixir/Phoenix applications that use Brunch / sass-brunch.

See https://github.com/erlang/docker-erlang-otp/issues/267 and https://github.com/c0b/docker-elixir/issues/131

**Comment by juulSme** [comment]
We've solved the issue for now by pointing our dependency to a specific git commit, i.e. `"sass-brunch": "https://github.com/brunch/sass-brunch.git#b21b27f6329c2ec30659daa0835db214dde708b0"` which I think is preferable to downgrading nodejs entirely or using a non-alpine or custom docker image.

**Comment by jkruse** [comment]
Version 3.0.0 was since released, and fixes this issue. Time to close?
